eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9411
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: zipkin-server
  datasource:
      url: jdbc:mysql://localhost:3306/spring-cloud-zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: lfhhfl
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
#spring.sleuth.sampler.percentage: 1.0
zipkin:
  storage:
    type: mysql