eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0 #即100%的概率将链路的数据上传给Zipkin Server，在默认的情况下，该值为0.1

#spring.zipkin.base-url=http://localhost:9411
